### ISSUE TITLE
Couldn't make it work either with v3.0.1 and v2.5.0

### ISSUE THREAD

**Issue by itwasnoteasy** [craigburke/lazybones-angular-grails#10]
I keep getting following errors:
{code}
username:ang-grails username$ ./gradlew run
Starting a new Gradle Daemon for this build (subsequent builds will be faster).

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/xxxxx/Desktop/ang-grails/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'ang-grails'.
> Failed to apply plugin [id 'grails']
   > Could not find method create() for arguments [main] on [].

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.315 secs
{code}

**Comment by craigburke** [comment]
This doesn't work with 3.0.1 (yet). 

So you're getting the same error with grails 2.5.0? Would you mind throwing the project you created with my template up on github so I can take a look?

**Comment by craigburke** [comment]
Nevermind, I can reproduce the problem with 2.5.0. I'll take a look.

**Comment by craigburke** [comment]
Apparently the grails gradle plugin doesn't play well with gradle 2.3+ I fixed this and published a new version of the template. You should be able to create a 2.5.0 app now.

**Comment by craigburke** [comment]
I'm going to close this. Feel free to reopen if your issue isn't resolved.

**Comment by calin014** [comment]
Hi,

First of all thanks for taking the time to look at what we did. The new
template worked for us. I'm not at work right now and i don't have time to
do the setup at home, so i'll get back to you with answers and details on
monday.

Have a great weekend,
Calin

**Comment by craigburke** [comment]
No problem. Hope it works out for you!
