### ISSUE TITLE
Grails 3.0

### ISSUE THREAD

**Issue by sapanparikh18** [craigburke/lazybones-angular-grails#13]
Hi Craig
When we start the app using gradlew it uses grails 2.5. While the Grails command does not run if we are using grails 3.0.
Can we get the same kind of template for the latest version of grails?

**Comment by craigburke** [comment]
@sapanparikh18 I stopped working on the Grails 3 version of this because it won't be necessary when the angular profile is released with Grails 3.1.

**Comment by sapanparikh18** [comment]
Are you trying the angular profile? I wish there was a one para tutorial
somewhere or at least order of steps.
