### ISSUE TITLE
Could not resolve all dependencies for configuration ':springloaded'. > null ext not allowed

### ISSUE THREAD

**Issue by jd73** [craigburke/lazybones-angular-grails#5]
I have been getting this error on gradle run with a nearly freshly generated application. The one change I made is to upgrade the grails-gradle-plugin version to 2.1.2 to fix another error I was getting when the application was run.

I am using groovy 2.3.9 and gradle 2.2.1. I have also tried with gradle 2.1 and 2.2 and groovy 2.3.7. An application generated with version 1.0 of the generator was able to run but got runtime errors.

When I run other gradle tasks like 'gradle dependencies' I get the same error but for other dependencies like ':bootstrap' instead of ':springloaded'.

Let me know if logs or stacktraces would be helpful for debugging the problem.

**Comment by craigburke** [comment]
Yeah there are some issues I guess with certain versions of the grails-gradle plugin and gradle 2.2+. I just released a new version of the template let me know if trying that helps.

**Comment by mcharrismak** [comment]
Hello Craig,
I have the same problem and cannot figure out how to proceed to make the application run. I am new to lazybones and gradle and not sure what is wrong with my setup. I am using gradle 2.4, groovy 2.3.10 and grails-gradle plugin 2.2.0.RC1, although i tried earlier versions of gradle including 2.0. I am using lazybones 0.8.1. The error i get is:

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':springloaded'.
> null ext not allowed
Also i think on bintray there is still the angular-grails v 1.1.6 template dates May 13th. I can see on github the more recent updates but I am not sure how to update my installation?

Please can you help?

**Comment by mcharrismak** [comment]
Hello again,

just tried with the new version 2.0.0-SNAPSHOT and the problem remains. I really wish i could use your template as I think it's awesome but I cannot at the moment. I have been able to create a domain class and a module but I cannot run the app.

Many thanks in advance

**Comment by craigburke** [comment]
2.0.0-SNAPSHOT isn't quite production ready, but hopefully I'll be able to cut a release of that sometime next week. It'll use Gradle 2.3 but 2.4 should also work.

For the current Grails 2.X version of the template you unfortunately can't use any version of Gradle beyond 2.2.

**Comment by mcharrismak** [comment]
Thank you so much for coming back to me so promptly,

I was just about to try with a lower version of grails. Thanks again and look forward to trying the new version!

**Comment by craigburke** [comment]
I'm closing this because the Grails Angular profile makes the new version of this unnecessary.
